### ISSUE TITLE
New settings / options for the URL's?

### ISSUE THREAD

**Issue by TexxMedia** [WebberZone/knowledgebase#5]
hi,
settings for the URL's would be great. It would be more flexible.
example: "kb-articles" => "questions" was for me better ;-)

**Comment by ajaydsouza** [comment]
Hi, That's one of the features I am planning in a future release.

**Comment by cedrickocher** [comment]
Hello,

Please, can you tell us if you're planning to improve the slugs of Knowledgebase? Because current URLs are really not friendly ("/knowledge-base/", "/kb-category/" ...).

Of course if you plan to add a field to set a custom slug, it's the best solution (like bbPress regarding forums). But can you tell us where we can modify the current slug manually please?

Even Yoast can't delete these specific slugs :-( !

Thank you,

Cédric

**Comment by ajaydsouza** [comment]
I plan on adding either a field or a filter to set the slug for both articles and the categories.

My current implementation has been because you tend to face the problem where if you have this and a page with the same slug, then this gets prioritised. However, I've been studying other plugins e.g. Easy Digital Downloads, and I plan to change the links to /knowledgebase/ in the next version as the default category slug.

You can find the code currently in https://github.com/WebberZone/knowledgebase/blob/master/includes/custom-post-type.php
You'll find the various instances in there for the slugs. e.g. kb-articles

**Comment by ajaydsouza** [comment]
Implemented as of: https://github.com/WebberZone/knowledgebase/commit/a318fcfa08b52dfb8997b8f6a57e8aeae2d2b419
